### ISSUE TITLE
Unable to open/generate using MPS 3.3.3 or MPS 3.3.4

### ISSUE THREAD

**Issue by nkoester** [CampagneLaboratory/ANTLR_MPS#3]
Hi, 

when trying to use the language, i get 650 errors after opening a freshly checked out version with MPS 3.3.3 (note: same with MPS 3.3.4). I doubt that these are actual errors but are rather related to missing libs/code or similar. Unfortunately I cannot find any information on dependencies or others usage instructions. I hope you can support me with this -- this could also be used as further documentation.

I am running MPS on an Arch Linux (Linux cuprit 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux) using Java "1.7.0_99" OpenJDK Runtime Environment (IcedTea 2.6.5) (Arch Linux build 7.u99_2.6.5-1-x86_64) OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

Here the commandline output of MPS:

```
[/home/nkoester/local/opt/MPS3.3.3/bin/] /home/nkoester/local/opt/MPS3.3.3/bin/mps.sh 
/home/nkoester/local/opt/MPS3.3.3/bin/mps.sh info: Using jdk located in /usr/lib/jvm/java-7-openjdk.
/home/nkoester/local/opt/MPS3.3.3/bin/mps.sh warning: Unknown operating system /usr/bin/uname. Do not know how to add PWD to libraries path.
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[   8463]   INFO - mps.library.LibraryInitializer - Adding libraries from jetbrains.mps.library.contributor.BootstrapLibraryContributor 
[   8464]   INFO - mps.library.LibraryInitializer - Adding libraries from jetbrains.mps.library.contributor.WorkbenchLibraryContributor 
[   8464]   INFO - mps.library.LibraryInitializer - Adding libraries from jetbrains.mps.library.contributor.PluginLibraryContributor 
[   8850]   INFO - mps.library.LibraryInitializer - Loading 110 libraries; Unloading 0 libraries. 
[  42640]   WARN - nplugins.BaseApplicationPlugin - Destination group was not found id: Internal. Trying to insert jetbrains.mps.ide.actions.ToolsInternal_ActionGroup 
[  43296]   INFO - s.plugins.PluginLoaderRegistry - Loading of 1 plugins took 0.877 s 
[  43730]   INFO - s.plugins.PluginLoaderRegistry - Loading of 128 plugins took 0.395 s 
[  43844]   INFO - s.plugins.PluginLoaderRegistry - Loading of 9 plugins took 0.110 s 
[  43845]   INFO - mps.library.LibraryInitializer - Adding libraries from jetbrains.mps.library.AdditionalLibrariesManager 
[  53848]   INFO - mps.library.LibraryInitializer - Adding libraries from jetbrains.mps.project.ProjectLibraryManager 
[  53885]   INFO - s.project.StandaloneMPSProject - Loading the project 'ANTLR' from disk 
[  55138]   INFO - s.project.StandaloneMPSProject - Project 'ANTLR' is opened 
[  55140]   INFO - rains.mps.project.ModuleLoader - Loading modules... 
[  55228]   WARN - lassloading.ClassLoadersHolder - Facet of the module ANTLR.persistence.build [solution] is not valid -- possibly the provided idea plugin (in the properties dialog/idea plugin facet tab) cannot be found among the bundled plugins 
[  55389]   INFO - rains.mps.project.ModuleLoader - Modules are loaded: 10 new; 0 removed 
[  55751]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.mps.editor2pdf 
[  55757]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.metar.R 
[  56974]   INFO - s.plugins.PluginLoaderRegistry - Loading of 5 plugins took 0.129 s 
[  56990]   INFO - de.make.StartupModuleMakerImpl - Making modules on startup 
[  57028]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.mps.editor2pdf 
[  57029]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.metar.R 
[  57168]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.mps.editor2pdf 
[  57170]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.metar.R 
[  57183]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.mps.editor2pdf 
[  57184]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.metar.R 
[  57208]   INFO - de.make.StartupModuleMakerImpl - Compilation on startup is finished 
[  57322]   INFO - jetbrains.mps.plugin.MPSPlugin - Wasn't able to connect to IDEA 
[  57984]   INFO - ctplugins.ProjectPluginManager - Loading of 143 project plugins took 0.353 s 
[  74973]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.mps.editor2pdf 
[  74973]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.metar.R 
[  74975]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.mps.editor2pdf 
[  74975]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.metar.R 
[  75022]   INFO - lassloading.ClassLoaderManager - Reloaded 11 module(s) in 0.100 s 
[  75022]   INFO - latform.watching.ReloadSession - File system reload finished in 2.281 s 
[  75200]   INFO - s.plugins.PluginLoaderRegistry - Unloading of 5 plugins took 0.046 s 
[  75321]   INFO - s.plugins.PluginLoaderRegistry - Loading of 5 plugins took 0.029 s 
[  77014]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.mps.editor2pdf 
[  77014]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.metar.R 
[  77191]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.mps.editor2pdf 
[  77191]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.metar.R 
[  77279]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.mps.editor2pdf 
[  77280]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.metar.R 
[  89578]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.Prog with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880685261. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89579]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880685262, while looking for constraints descriptor. 
[  89579]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.RScript with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880685262. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89580]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/1826877622977697003, while looking for constraints descriptor. 
[  89581]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.EmptyLine with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/1826877622977697003. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89581]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.BinaryOperatorExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6247096756517946181. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89581]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707754, while looking for constraints descriptor. 
[  89582]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.AssignmentOperatorExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707754. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89582]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.FunctionCallExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707756. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89582]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707756, while looking for constraints descriptor. 
[  89583]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.HelpExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707763. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89583]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707763, while looking for constraints descriptor. 
[  89584]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.IfExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707758. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89584]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707758, while looking for constraints descriptor. 
[  89585]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.ForExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707760. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89585]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707760, while looking for constraints descriptor. 
[  89586]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707777, while looking for constraints descriptor. 
[  89587]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.TrueLiteralExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707777. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89588]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707767, while looking for constraints descriptor. 
[  89588]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.Identifier with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707767. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89588]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.FunctionDeclarationExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707755. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89588]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707755, while looking for constraints descriptor. 
[  89589]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/489068675543418436, while looking for constraints descriptor. 
[  89589]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.SimpleAssignment with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/489068675543418436. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89589]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.ParameterValues with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/5770663561153557551. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89590]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/5770663561153557551, while looking for constraints descriptor. 
[  89590]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.FunctionIdRef with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/7431839982580115597. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89590]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.IdentifierRef with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/1499760628227103368. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89590]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/7431839982580115597, while looking for constraints descriptor. 
[  89592]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.UnaryOperatorExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707743. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89592]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707749, while looking for constraints descriptor. 
[  89593]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.NotExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707749. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89593]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.BodyExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707757. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89593]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707757, while looking for constraints descriptor. 
[  89595]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707768, while looking for constraints descriptor. 
[  89595]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.StringLiteralExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707768. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89597]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707748, while looking for constraints descriptor. 
[  89597]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.ComparisonExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707748. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89598]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.FunctionParamDeclarationList with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/4798834304115080351. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89599]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/4798834304115080351, while looking for constraints descriptor. 
[  89599]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.ParameterValue with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/5770663561153558147. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89599]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/4933197140516011540, while looking for constraints descriptor. 
[  89600]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.ParameterValueWithId with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/4933197140516011540. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89600]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/4933197140516011539, while looking for constraints descriptor. 
[  89600]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.PositionalParameterValue with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/4933197140516011539. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89602]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/489068675575040827, while looking for constraints descriptor. 
[  89602]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.Not with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/489068675575040827. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89603]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.Exprlist with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/3737166271522079190. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89603]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/3737166271522079190, while looking for constraints descriptor. 
[  89605]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/1499760628227103368, while looking for constraints descriptor. 
[  89606]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707770, while looking for constraints descriptor. 
[  89607]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.IntLiteralExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707770. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89607]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/489068675543418428, while looking for constraints descriptor. 
[  89607]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.GreaterThan with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/489068675543418428. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89609]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.ParameterDeclaration with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/4798834304115080350. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89609]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/4798834304115080350, while looking for constraints descriptor. 
[  89610]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/411958952822325619, while looking for constraints descriptor. 
[  89610]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.EmptyExprlist with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/411958952822325619. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89611]   WARN - l.language.ConstraintsRegistry - No language for: 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707778, while looking for constraints descriptor. 
[  89611]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.FalseLiteralExpr with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/6176023809880707778. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 
[  89633]   WARN - l.language.ConstraintsRegistry - No language for: 93bc01ac-08ca-4f11-9c7d-614d04055dfb/893392931327129896, while looking for constraints descriptor. 
[  89634]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.mps.editor2pdf.structure.DiagramOutputDirectory with id 93bc01ac-08ca-4f11-9c7d-614d04055dfb/893392931327129896. Please check the language org.campagnelab.mps.editor2pdf with id 93bc01ac-08ca-4f11-9c7d-614d04055dfb is built and compiled. 
[  92177]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.mps.editor2pdf 
[  92178]   WARN - ntimesOfUsedLanguageCalculator - The source module of the used language cannot be found: org.campagnelab.metar.R 
[  94449]  ERROR - lassloading.ClassLoaderManager - Exception during class loading 
jetbrains.mps.classloading.ModuleClassNotFoundException: Unable to load class: org.campagnelab.ANTLR.structure.LABELING_OPERATOR_PropertySupport using ModuleClassLoader of org.campagnelab.ANTLR module
    at jetbrains.mps.classloading.ModuleClassLoader.createCLNFException(ModuleClassLoader.java:136)
    at jetbrains.mps.classloading.ModuleClassLoader.loadClass(ModuleClassLoader.java:123)
    at jetbrains.mps.classloading.ModuleClassLoader.loadClass(ModuleClassLoader.java:90)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at jetbrains.mps.module.ReloadableModuleBase.getClass(ReloadableModuleBase.java:71)
    at jetbrains.mps.smodel.Language.getClass(Language.java:435)
    at jetbrains.mps.module.ReloadableModuleBase.getClass(ReloadableModuleBase.java:52)
    at jetbrains.mps.classloading.ClassLoaderManager.getClass(ClassLoaderManager.java:230)
    at jetbrains.mps.smodel.PropertySupport.loadPropertySupport(PropertySupport.java:197)
    at jetbrains.mps.smodel.PropertySupport.access$400(PropertySupport.java:45)
    at jetbrains.mps.smodel.PropertySupport$1.compute(PropertySupport.java:169)
    at jetbrains.mps.smodel.PropertySupport$1.compute(PropertySupport.java:147)
    at jetbrains.mps.smodel.NodeReadAccessCasterInEditor.runReadTransparentAction(NodeReadAccessCasterInEditor.java:100)
    at jetbrains.mps.smodel.PropertySupport.getPropertySupport(PropertySupport.java:147)
    at jetbrains.mps.checkers.ConstraintsChecker.checkNode(ConstraintsChecker.java:133)
    at jetbrains.mps.checkers.LanguageErrorsComponent.check(LanguageErrorsComponent.java:205)
    at jetbrains.mps.checkers.LanguageChecker.getErrors(LanguageChecker.java:23)
    at jetbrains.mps.ide.modelchecker.platform.actions.INodeCheckerSpecificCheckerAdapter.checkModel(INodeCheckerSpecificCheckerAdapter.java:33)
    at jetbrains.mps.ide.modelchecker.platform.actions.ModelChecker.checkModel(ModelChecker.java:44)
    at jetbrains.mps.ide.modelchecker.platform.actions.ModelCheckerIssueFinder.find(ModelCheckerIssueFinder.java:84)
    at jetbrains.mps.ide.findusages.findalgorithm.resultproviders.treenodes.FinderNode$1.compute(FinderNode.java:78)
    at jetbrains.mps.ide.findusages.findalgorithm.resultproviders.treenodes.FinderNode$1.compute(FinderNode.java:74)
    at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:115)
    at jetbrains.mps.ide.findusages.findalgorithm.resultproviders.treenodes.FinderNode.doGetResults(FinderNode.java:74)
    at jetbrains.mps.ide.findusages.findalgorithm.resultproviders.treenodes.BaseNode.getResults(BaseNode.java:89)
    at jetbrains.mps.ide.findusages.findalgorithm.resultproviders.treenodes.UnionNode.doGetResults(UnionNode.java:31)
    at jetbrains.mps.ide.findusages.findalgorithm.resultproviders.treenodes.BaseNode.getResults(BaseNode.java:89)
    at jetbrains.mps.ide.findusages.view.UsagesView$SearchTask.run(UsagesView.java:370)
    at jetbrains.mps.smodel.WorkbenchModelAccess$2.run(WorkbenchModelAccess.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:943)
    at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:99)
    at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:53)
    at jetbrains.mps.ide.findusages.view.UsagesView$SearchTask.execute(UsagesView.java:364)
    at jetbrains.mps.ide.findusages.view.UsagesView$RerunAction$1.run(UsagesView.java:316)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl$14$1.run(ApplicationImpl.java:626)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
[  94453]  ERROR - ins.mps.smodel.PropertySupport - Can't find a class org.campagnelab.ANTLR.structure.LABELING_OPERATOR_PropertySupport 
[ 129137]   WARN - ins.mps.smodel.StaticReference - Could not resolve reference 'baseMethodDeclaration' from MetaIdByDeclaration.null.
r:329b6dc0-d0cf-4a3f-8195-a457c0883f44(org.campagnelab.antlr.persistence.impl)/6657565819858187150
 -- target model '6ed54515-acc8-4d1e-a16c-9fd6cfe951ea/java:jetbrains.mps.smodel.adapter.ids(MPS.Core/)' doesn't contain node with id=~MetaIdByDeclaration.ref2Id(org.jetbrains.mps.openapi.module.SModuleReference):org.jetbrains.mps.openapi.language.SLanguage 
[ 129242]   WARN - ins.mps.smodel.StaticReference - Could not resolve reference 'baseMethodDeclaration' from MetaIdByDeclaration.null.
r:329b6dc0-d0cf-4a3f-8195-a457c0883f44(org.campagnelab.antlr.persistence.impl)/6811693360202856901
 -- target model '6ed54515-acc8-4d1e-a16c-9fd6cfe951ea/java:jetbrains.mps.smodel.adapter.ids(MPS.Core/)' doesn't contain node with id=~MetaIdByDeclaration.ref2Id(org.jetbrains.mps.openapi.module.SModuleReference):org.jetbrains.mps.openapi.language.SLanguage 
[ 150200]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.RScript, while looking for the behavior descriptor. 
[ 150202]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.FunctionDeclarationExpr, while looking for the behavior descriptor. 
[ 150202]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.FunctionCallExpr, while looking for the behavior descriptor. 
[ 150203]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.HelpExpr, while looking for the behavior descriptor. 
[ 150205]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.BodyExpr, while looking for the behavior descriptor. 
[ 150206]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.ParameterValueWithId, while looking for the behavior descriptor. 
[ 150206]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.PositionalParameterValue, while looking for the behavior descriptor. 
[ 150207]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.ForExpr, while looking for the behavior descriptor. 
[ 150209]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.ParameterValues, while looking for the behavior descriptor. 
[ 150210]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.AssignmentOperatorExpr, while looking for the behavior descriptor. 
[ 150216]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.IfExpr, while looking for the behavior descriptor. 
[ 150235]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.Exprlist, while looking for the behavior descriptor. 
[ 150245]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.NotExpr, while looking for the behavior descriptor. 
[ 150260]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.EmptyExprlist, while looking for the behavior descriptor. 
[ 150263]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.ComparisonExpr, while looking for the behavior descriptor. 
[ 150273]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.ParameterDeclaration, while looking for the behavior descriptor. 
[ 150309]   WARN - behaviour.BehaviorRegistryImpl - No language for: org.campagnelab.metar.R.structure.FunctionParamDeclarationList, while looking for the behavior descriptor. 
[ 338513]   WARN - legal.IllegalConceptDescriptor - IllegalConceptDescriptor created for concept org.campagnelab.metar.R.structure.BooleanLiteral with id 3b58810c-8431-4bbb-99ea-b4671e02dd13/1229604057012669901. Please check the language org.campagnelab.metar.R with id 3b58810c-8431-4bbb-99ea-b4671e02dd13 is built and compiled. 

```

Cheers

**Comment by fac2003** [comment]
Sorry about this problem and thanks for reporting it. We had migrated the project in our Bitbucket repo but had not pushed these changes to GitHub. I've just pushed the latest version, which hopefully will work for you, if not reopen.

**Comment by nkoester** [comment]
No problem! Thanks for the quick update!

I've retried using MPS 3.3.4, however the exception still occurs:

```
Exception during class loading: Unable to load class: org.campagnelab.ANTLR.structure.LABELING_OPERATOR_PropertySupport using ModuleClassLoader of org.campagnelab.ANTLR module
jetbrains.mps.classloading.ModuleClassNotFoundException: Unable to load class: org.campagnelab.ANTLR.structure.LABELING_OPERATOR_PropertySupport using ModuleClassLoader of org.campagnelab.ANTLR module
    at jetbrains.mps.classloading.ModuleClassLoader.createCLNFException(ModuleClassLoader.java:136)
    at jetbrains.mps.classloading.ModuleClassLoader.loadClass(ModuleClassLoader.java:123)
    at jetbrains.mps.classloading.ModuleClassLoader.loadClass(ModuleClassLoader.java:90)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at jetbrains.mps.module.ReloadableModuleBase.getClass(ReloadableModuleBase.java:71)
    at jetbrains.mps.smodel.Language.getClass(Language.java:435)
    at jetbrains.mps.module.ReloadableModuleBase.getClass(ReloadableModuleBase.java:52)
    at jetbrains.mps.classloading.ClassLoaderManager.getClass(ClassLoaderManager.java:230)
    at jetbrains.mps.smodel.PropertySupport.loadPropertySupport(PropertySupport.java:197)
    at jetbrains.mps.smodel.PropertySupport.access$400(PropertySupport.java:45)
    at jetbrains.mps.smodel.PropertySupport$1.compute(PropertySupport.java:169)
    at jetbrains.mps.smodel.PropertySupport$1.compute(PropertySupport.java:147)
    at jetbrains.mps.smodel.NodeReadAccessCasterInEditor.runReadTransparentAction(NodeReadAccessCasterInEditor.java:100)
    at jetbrains.mps.smodel.PropertySupport.getPropertySupport(PropertySupport.java:147)
    at jetbrains.mps.checkers.ConstraintsChecker.checkNode(ConstraintsChecker.java:133)
    at jetbrains.mps.checkers.LanguageErrorsComponent.check(LanguageErrorsComponent.java:205)
    at jetbrains.mps.checkers.LanguageChecker.getErrors(LanguageChecker.java:23)
    at jetbrains.mps.ide.modelchecker.platform.actions.INodeCheckerSpecificCheckerAdapter.checkModel(INodeCheckerSpecificCheckerAdapter.java:41)
    at jetbrains.mps.ide.modelchecker.platform.actions.ModelChecker.checkModel(ModelChecker.java:44)
    at jetbrains.mps.ide.modelchecker.platform.actions.ModelCheckerIssueFinder.find(ModelCheckerIssueFinder.java:84)
    at jetbrains.mps.ide.findusages.findalgorithm.resultproviders.treenodes.FinderNode$1.compute(FinderNode.java:78)
    at jetbrains.mps.ide.findusages.findalgorithm.resultproviders.treenodes.FinderNode$1.compute(FinderNode.java:74)
    at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:115)
    at jetbrains.mps.ide.findusages.findalgorithm.resultproviders.treenodes.FinderNode.doGetResults(FinderNode.java:74)
    at jetbrains.mps.ide.findusages.findalgorithm.resultproviders.treenodes.BaseNode.getResults(BaseNode.java:89)
    at jetbrains.mps.ide.findusages.findalgorithm.resultproviders.treenodes.UnionNode.doGetResults(UnionNode.java:31)
    at jetbrains.mps.ide.findusages.findalgorithm.resultproviders.treenodes.BaseNode.getResults(BaseNode.java:89)
    at jetbrains.mps.ide.findusages.view.UsagesView$SearchTask.run(UsagesView.java:370)
    at jetbrains.mps.smodel.WorkbenchModelAccess$2.run(WorkbenchModelAccess.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:943)
    at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:99)
    at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:53)
    at jetbrains.mps.ide.findusages.view.UsagesView$SearchTask.execute(UsagesView.java:364)
    at jetbrains.mps.ide.findusages.view.UsagesView$RerunAction$1.run(UsagesView.java:316)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl$14$1.run(ApplicationImpl.java:626)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

And after the model checking still 20 errors remain unsolved. See this image for a broad overview:

![errors](https://cloud.githubusercontent.com/assets/6061519/14277809/1bb771b8-fb25-11e5-8e24-995f7413e77c.png)

Any ideas?

**Comment by fac2003** [comment]
I see it now. You are building with validation enabled, when we build with it disabled (it generates a lot of false positives in my experience, useful to have a look once in a while, but we end up disabling it in most projects).
